/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Sequences {

  /**
   * The sequence <code>public.shareable_entity_id_seq</code>
   */
  public static final Sequence<Long> SHAREABLE_ENTITY_ID_SEQ = Internal.createSequence("shareable_entity_id_seq",
      JPublic.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
