/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JClusters;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JClustersRecord extends UpdatableRecordImpl<JClustersRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.clusters.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.clusters.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.clusters.index_id</code>.
   */
  public void setIndexId(Long value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.clusters.index_id</code>.
   */
  public Long getIndexId() {
    return (Long) get(1);
  }

  /**
   * Setter for <code>public.clusters.project_id</code>.
   */
  public void setProjectId(Long value) {
    set(2, value);
  }

  /**
   * Getter for <code>public.clusters.project_id</code>.
   */
  public Long getProjectId() {
    return (Long) get(2);
  }

  /**
   * Setter for <code>public.clusters.launch_id</code>.
   */
  public void setLaunchId(Long value) {
    set(3, value);
  }

  /**
   * Getter for <code>public.clusters.launch_id</code>.
   */
  public Long getLaunchId() {
    return (Long) get(3);
  }

  /**
   * Setter for <code>public.clusters.message</code>.
   */
  public void setMessage(String value) {
    set(4, value);
  }

  /**
   * Getter for <code>public.clusters.message</code>.
   */
  public String getMessage() {
    return (String) get(4);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JClustersRecord
   */
  public JClustersRecord() {
    super(JClusters.CLUSTERS);
  }

  /**
   * Create a detached, initialised JClustersRecord
   */
  public JClustersRecord(Long id, Long indexId, Long projectId, Long launchId, String message) {
    super(JClusters.CLUSTERS);

    setId(id);
    setIndexId(indexId);
    setProjectId(projectId);
    setLaunchId(launchId);
    setMessage(message);
    resetChangedOnNotNull();
  }
}
