/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JCounterDecrease;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JCounterDecreaseRecord extends TableRecordImpl<JCounterDecreaseRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.counter_decrease.s_counter</code>.
   */
  public void setSCounter(Integer value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.counter_decrease.s_counter</code>.
   */
  public Integer getSCounter() {
    return (Integer) get(0);
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JCounterDecreaseRecord
   */
  public JCounterDecreaseRecord() {
    super(JCounterDecrease.COUNTER_DECREASE);
  }

  /**
   * Create a detached, initialised JCounterDecreaseRecord
   */
  public JCounterDecreaseRecord(Integer sCounter) {
    super(JCounterDecrease.COUNTER_DECREASE);

    setSCounter(sCounter);
    resetChangedOnNotNull();
  }
}
