/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JFilter;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JFilterRecord extends UpdatableRecordImpl<JFilterRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.filter.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.filter.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.filter.name</code>.
   */
  public void setName(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.filter.name</code>.
   */
  public String getName() {
    return (String) get(1);
  }

  /**
   * Setter for <code>public.filter.target</code>.
   */
  public void setTarget(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>public.filter.target</code>.
   */
  public String getTarget() {
    return (String) get(2);
  }

  /**
   * Setter for <code>public.filter.description</code>.
   */
  public void setDescription(String value) {
    set(3, value);
  }

  /**
   * Getter for <code>public.filter.description</code>.
   */
  public String getDescription() {
    return (String) get(3);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JFilterRecord
   */
  public JFilterRecord() {
    super(JFilter.FILTER);
  }

  /**
   * Create a detached, initialised JFilterRecord
   */
  public JFilterRecord(Long id, String name, String target, String description) {
    super(JFilter.FILTER);

    setId(id);
    setName(name);
    setTarget(target);
    setDescription(description);
    resetChangedOnNotNull();
  }
}
