/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JGroupsProjects;
import java.time.Instant;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JGroupsProjectsRecord extends UpdatableRecordImpl<JGroupsProjectsRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.groups_projects.group_id</code>.
   */
  public void setGroupId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.groups_projects.group_id</code>.
   */
  public Long getGroupId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.groups_projects.project_id</code>.
   */
  public void setProjectId(Long value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.groups_projects.project_id</code>.
   */
  public Long getProjectId() {
    return (Long) get(1);
  }

  /**
   * Setter for <code>public.groups_projects.project_role</code>.
   */
  public void setProjectRole(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>public.groups_projects.project_role</code>.
   */
  public String getProjectRole() {
    return (String) get(2);
  }

  /**
   * Setter for <code>public.groups_projects.created_at</code>.
   */
  public void setCreatedAt(Instant value) {
    set(3, value);
  }

  /**
   * Getter for <code>public.groups_projects.created_at</code>.
   */
  public Instant getCreatedAt() {
    return (Instant) get(3);
  }

  /**
   * Setter for <code>public.groups_projects.updated_at</code>.
   */
  public void setUpdatedAt(Instant value) {
    set(4, value);
  }

  /**
   * Getter for <code>public.groups_projects.updated_at</code>.
   */
  public Instant getUpdatedAt() {
    return (Instant) get(4);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record2<Long, Long> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JGroupsProjectsRecord
   */
  public JGroupsProjectsRecord() {
    super(JGroupsProjects.GROUPS_PROJECTS);
  }

  /**
   * Create a detached, initialised JGroupsProjectsRecord
   */
  public JGroupsProjectsRecord(Long groupId, Long projectId, String projectRole, Instant createdAt, Instant updatedAt) {
    super(JGroupsProjects.GROUPS_PROJECTS);

    setGroupId(groupId);
    setProjectId(projectId);
    setProjectRole(projectRole);
    setCreatedAt(createdAt);
    setUpdatedAt(updatedAt);
    resetChangedOnNotNull();
  }
}
