/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JLaunchNumber;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JLaunchNumberRecord extends UpdatableRecordImpl<JLaunchNumberRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.launch_number.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.launch_number.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.launch_number.project_id</code>.
   */
  public void setProjectId(Long value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.launch_number.project_id</code>.
   */
  public Long getProjectId() {
    return (Long) get(1);
  }

  /**
   * Setter for <code>public.launch_number.launch_name</code>.
   */
  public void setLaunchName(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>public.launch_number.launch_name</code>.
   */
  public String getLaunchName() {
    return (String) get(2);
  }

  /**
   * Setter for <code>public.launch_number.number</code>.
   */
  public void setNumber(Integer value) {
    set(3, value);
  }

  /**
   * Getter for <code>public.launch_number.number</code>.
   */
  public Integer getNumber() {
    return (Integer) get(3);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JLaunchNumberRecord
   */
  public JLaunchNumberRecord() {
    super(JLaunchNumber.LAUNCH_NUMBER);
  }

  /**
   * Create a detached, initialised JLaunchNumberRecord
   */
  public JLaunchNumberRecord(Long id, Long projectId, String launchName, Integer number) {
    super(JLaunchNumber.LAUNCH_NUMBER);

    setId(id);
    setProjectId(projectId);
    setLaunchName(launchName);
    setNumber(number);
    resetChangedOnNotNull();
  }
}
