/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JLaunchNames;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JLaunchNamesRecord extends TableRecordImpl<JLaunchNamesRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.launch_names.sender_case_id</code>.
   */
  public void setSenderCaseId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.launch_names.sender_case_id</code>.
   */
  public Long getSenderCaseId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.launch_names.launch_name</code>.
   */
  public void setLaunchName(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.launch_names.launch_name</code>.
   */
  public String getLaunchName() {
    return (String) get(1);
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JLaunchNamesRecord
   */
  public JLaunchNamesRecord() {
    super(JLaunchNames.LAUNCH_NAMES);
  }

  /**
   * Create a detached, initialised JLaunchNamesRecord
   */
  public JLaunchNamesRecord(Long senderCaseId, String launchName) {
    super(JLaunchNames.LAUNCH_NAMES);

    setSenderCaseId(senderCaseId);
    setLaunchName(launchName);
    resetChangedOnNotNull();
  }
}
