/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.enums.JOrganizationRoleEnum;
import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JOrganizationUser;
import java.time.Instant;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JOrganizationUserRecord extends UpdatableRecordImpl<JOrganizationUserRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.organization_user.user_id</code>.
   */
  public void setUserId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.organization_user.user_id</code>.
   */
  public Long getUserId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.organization_user.organization_id</code>.
   */
  public void setOrganizationId(Long value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.organization_user.organization_id</code>.
   */
  public Long getOrganizationId() {
    return (Long) get(1);
  }

  /**
   * Setter for <code>public.organization_user.organization_role</code>.
   */
  public void setOrganizationRole(JOrganizationRoleEnum value) {
    set(2, value);
  }

  /**
   * Getter for <code>public.organization_user.organization_role</code>.
   */
  public JOrganizationRoleEnum getOrganizationRole() {
    return (JOrganizationRoleEnum) get(2);
  }

  /**
   * Setter for <code>public.organization_user.assigned_at</code>.
   */
  public void setAssignedAt(Instant value) {
    set(3, value);
  }

  /**
   * Getter for <code>public.organization_user.assigned_at</code>.
   */
  public Instant getAssignedAt() {
    return (Instant) get(3);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record2<Long, Long> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JOrganizationUserRecord
   */
  public JOrganizationUserRecord() {
    super(JOrganizationUser.ORGANIZATION_USER);
  }

  /**
   * Create a detached, initialised JOrganizationUserRecord
   */
  public JOrganizationUserRecord(Long userId, Long organizationId, JOrganizationRoleEnum organizationRole,
      Instant assignedAt) {
    super(JOrganizationUser.ORGANIZATION_USER);

    setUserId(userId);
    setOrganizationId(organizationId);
    setOrganizationRole(organizationRole);
    setAssignedAt(assignedAt);
    resetChangedOnNotNull();
  }
}
