/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JParameter;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JParameterRecord extends TableRecordImpl<JParameterRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.parameter.item_id</code>.
   */
  public void setItemId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.parameter.item_id</code>.
   */
  public Long getItemId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.parameter.key</code>.
   */
  public void setKey(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.parameter.key</code>.
   */
  public String getKey() {
    return (String) get(1);
  }

  /**
   * Setter for <code>public.parameter.value</code>.
   */
  public void setValue(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>public.parameter.value</code>.
   */
  public String getValue() {
    return (String) get(2);
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JParameterRecord
   */
  public JParameterRecord() {
    super(JParameter.PARAMETER);
  }

  /**
   * Create a detached, initialised JParameterRecord
   */
  public JParameterRecord(Long itemId, String key, String value) {
    super(JParameter.PARAMETER);

    setItemId(itemId);
    setKey(key);
    setValue(value);
    resetChangedOnNotNull();
  }
}
