/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JPatternTemplateTestItem;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JPatternTemplateTestItemRecord extends UpdatableRecordImpl<JPatternTemplateTestItemRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.pattern_template_test_item.pattern_id</code>.
   */
  public void setPatternId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.pattern_template_test_item.pattern_id</code>.
   */
  public Long getPatternId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.pattern_template_test_item.item_id</code>.
   */
  public void setItemId(Long value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.pattern_template_test_item.item_id</code>.
   */
  public Long getItemId() {
    return (Long) get(1);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record2<Long, Long> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JPatternTemplateTestItemRecord
   */
  public JPatternTemplateTestItemRecord() {
    super(JPatternTemplateTestItem.PATTERN_TEMPLATE_TEST_ITEM);
  }

  /**
   * Create a detached, initialised JPatternTemplateTestItemRecord
   */
  public JPatternTemplateTestItemRecord(Long patternId, Long itemId) {
    super(JPatternTemplateTestItem.PATTERN_TEMPLATE_TEST_ITEM);

    setPatternId(patternId);
    setItemId(itemId);
    resetChangedOnNotNull();
  }
}
