/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.enums.JProjectRoleEnum;
import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JProjectUser;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JProjectUserRecord extends UpdatableRecordImpl<JProjectUserRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.project_user.user_id</code>.
   */
  public void setUserId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.project_user.user_id</code>.
   */
  public Long getUserId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.project_user.project_id</code>.
   */
  public void setProjectId(Long value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.project_user.project_id</code>.
   */
  public Long getProjectId() {
    return (Long) get(1);
  }

  /**
   * Setter for <code>public.project_user.project_role</code>.
   */
  public void setProjectRole(JProjectRoleEnum value) {
    set(2, value);
  }

  /**
   * Getter for <code>public.project_user.project_role</code>.
   */
  public JProjectRoleEnum getProjectRole() {
    return (JProjectRoleEnum) get(2);
  }

  /**
   * Setter for <code>public.project_user.project_role_backup</code>.
   */
  public void setProjectRoleBackup(String value) {
    set(3, value);
  }

  /**
   * Getter for <code>public.project_user.project_role_backup</code>.
   */
  public String getProjectRoleBackup() {
    return (String) get(3);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record2<Long, Long> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JProjectUserRecord
   */
  public JProjectUserRecord() {
    super(JProjectUser.PROJECT_USER);
  }

  /**
   * Create a detached, initialised JProjectUserRecord
   */
  public JProjectUserRecord(Long userId, Long projectId, JProjectRoleEnum projectRole, String projectRoleBackup) {
    super(JProjectUser.PROJECT_USER);

    setUserId(userId);
    setProjectId(projectId);
    setProjectRole(projectRole);
    setProjectRoleBackup(projectRoleBackup);
    resetChangedOnNotNull();
  }
}
