/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JRecipients;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JRecipientsRecord extends TableRecordImpl<JRecipientsRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.recipients.sender_case_id</code>.
   */
  public void setSenderCaseId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.recipients.sender_case_id</code>.
   */
  public Long getSenderCaseId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.recipients.recipient</code>.
   */
  public void setRecipient(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.recipients.recipient</code>.
   */
  public String getRecipient() {
    return (String) get(1);
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JRecipientsRecord
   */
  public JRecipientsRecord() {
    super(JRecipients.RECIPIENTS);
  }

  /**
   * Create a detached, initialised JRecipientsRecord
   */
  public JRecipientsRecord(Long senderCaseId, String recipient) {
    super(JRecipients.RECIPIENTS);

    setSenderCaseId(senderCaseId);
    setRecipient(recipient);
    resetChangedOnNotNull();
  }
}
