/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JShedlock;
import java.time.Instant;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JShedlockRecord extends UpdatableRecordImpl<JShedlockRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.shedlock.name</code>.
   */
  public void setName(String value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.shedlock.name</code>.
   */
  public String getName() {
    return (String) get(0);
  }

  /**
   * Setter for <code>public.shedlock.lock_until</code>.
   */
  public void setLockUntil(Instant value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.shedlock.lock_until</code>.
   */
  public Instant getLockUntil() {
    return (Instant) get(1);
  }

  /**
   * Setter for <code>public.shedlock.locked_at</code>.
   */
  public void setLockedAt(Instant value) {
    set(2, value);
  }

  /**
   * Getter for <code>public.shedlock.locked_at</code>.
   */
  public Instant getLockedAt() {
    return (Instant) get(2);
  }

  /**
   * Setter for <code>public.shedlock.locked_by</code>.
   */
  public void setLockedBy(String value) {
    set(3, value);
  }

  /**
   * Getter for <code>public.shedlock.locked_by</code>.
   */
  public String getLockedBy() {
    return (String) get(3);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<String> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JShedlockRecord
   */
  public JShedlockRecord() {
    super(JShedlock.SHEDLOCK);
  }

  /**
   * Create a detached, initialised JShedlockRecord
   */
  public JShedlockRecord(String name, Instant lockUntil, Instant lockedAt, String lockedBy) {
    super(JShedlock.SHEDLOCK);

    setName(name);
    setLockUntil(lockUntil);
    setLockedAt(lockedAt);
    setLockedBy(lockedBy);
    resetChangedOnNotNull();
  }
}
