/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JStatistics;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JStatisticsRecord extends UpdatableRecordImpl<JStatisticsRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.statistics.s_id</code>.
   */
  public void setSId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.statistics.s_id</code>.
   */
  public Long getSId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.statistics.s_counter</code>.
   */
  public void setSCounter(Integer value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.statistics.s_counter</code>.
   */
  public Integer getSCounter() {
    return (Integer) get(1);
  }

  /**
   * Setter for <code>public.statistics.launch_id</code>.
   */
  public void setLaunchId(Long value) {
    set(2, value);
  }

  /**
   * Getter for <code>public.statistics.launch_id</code>.
   */
  public Long getLaunchId() {
    return (Long) get(2);
  }

  /**
   * Setter for <code>public.statistics.item_id</code>.
   */
  public void setItemId(Long value) {
    set(3, value);
  }

  /**
   * Getter for <code>public.statistics.item_id</code>.
   */
  public Long getItemId() {
    return (Long) get(3);
  }

  /**
   * Setter for <code>public.statistics.statistics_field_id</code>.
   */
  public void setStatisticsFieldId(Long value) {
    set(4, value);
  }

  /**
   * Getter for <code>public.statistics.statistics_field_id</code>.
   */
  public Long getStatisticsFieldId() {
    return (Long) get(4);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JStatisticsRecord
   */
  public JStatisticsRecord() {
    super(JStatistics.STATISTICS);
  }

  /**
   * Create a detached, initialised JStatisticsRecord
   */
  public JStatisticsRecord(Long sId, Integer sCounter, Long launchId, Long itemId, Long statisticsFieldId) {
    super(JStatistics.STATISTICS);

    setSId(sId);
    setSCounter(sCounter);
    setLaunchId(launchId);
    setItemId(itemId);
    setStatisticsFieldId(statisticsFieldId);
    resetChangedOnNotNull();
  }
}
