/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JStatisticsField;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JStatisticsFieldRecord extends UpdatableRecordImpl<JStatisticsFieldRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.statistics_field.sf_id</code>.
   */
  public void setSfId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.statistics_field.sf_id</code>.
   */
  public Long getSfId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.statistics_field.name</code>.
   */
  public void setName(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.statistics_field.name</code>.
   */
  public String getName() {
    return (String) get(1);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JStatisticsFieldRecord
   */
  public JStatisticsFieldRecord() {
    super(JStatisticsField.STATISTICS_FIELD);
  }

  /**
   * Create a detached, initialised JStatisticsFieldRecord
   */
  public JStatisticsFieldRecord(Long sfId, String name) {
    super(JStatisticsField.STATISTICS_FIELD);

    setSfId(sfId);
    setName(name);
    resetChangedOnNotNull();
  }
}
