/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.enums.JStatusEnum;
import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JTestItemResults;
import java.time.Instant;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class JTestItemResultsRecord extends UpdatableRecordImpl<JTestItemResultsRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.test_item_results.result_id</code>.
   */
  public void setResultId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.test_item_results.result_id</code>.
   */
  public Long getResultId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.test_item_results.status</code>.
   */
  public void setStatus(JStatusEnum value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.test_item_results.status</code>.
   */
  public JStatusEnum getStatus() {
    return (JStatusEnum) get(1);
  }

  /**
   * Setter for <code>public.test_item_results.end_time</code>.
   */
  public void setEndTime(Instant value) {
    set(2, value);
  }

  /**
   * Getter for <code>public.test_item_results.end_time</code>.
   */
  public Instant getEndTime() {
    return (Instant) get(2);
  }

  /**
   * Setter for <code>public.test_item_results.duration</code>.
   */
  public void setDuration(Double value) {
    set(3, value);
  }

  /**
   * Getter for <code>public.test_item_results.duration</code>.
   */
  public Double getDuration() {
    return (Double) get(3);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached JTestItemResultsRecord
   */
  public JTestItemResultsRecord() {
    super(JTestItemResults.TEST_ITEM_RESULTS);
  }

  /**
   * Create a detached, initialised JTestItemResultsRecord
   */
  public JTestItemResultsRecord(Long resultId, JStatusEnum status, Instant endTime, Double duration) {
    super(JTestItemResults.TEST_ITEM_RESULTS);

    setResultId(resultId);
    setStatus(status);
    setEndTime(endTime);
    setDuration(duration);
    resetChangedOnNotNull();
  }
}
