/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JTmsTestCaseLaunch;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JTmsTestCaseLaunchRecord extends UpdatableRecordImpl<JTmsTestCaseLaunchRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tms_test_case_launch.test_case_id</code>.
     */
    public void setTestCaseId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tms_test_case_launch.test_case_id</code>.
     */
    public Long getTestCaseId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tms_test_case_launch.launch_id</code>.
     */
    public void setLaunchId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tms_test_case_launch.launch_id</code>.
     */
    public Long getLaunchId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JTmsTestCaseLaunchRecord
     */
    public JTmsTestCaseLaunchRecord() {
        super(JTmsTestCaseLaunch.TMS_TEST_CASE_LAUNCH);
    }

    /**
     * Create a detached, initialised JTmsTestCaseLaunchRecord
     */
    public JTmsTestCaseLaunchRecord(Long testCaseId, Long launchId) {
        super(JTmsTestCaseLaunch.TMS_TEST_CASE_LAUNCH);

        setTestCaseId(testCaseId);
        setLaunchId(launchId);
        resetChangedOnNotNull();
    }
}
