/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JTmsDatasetData;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JTmsDatasetDataRecord extends UpdatableRecordImpl<JTmsDatasetDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tms_dataset_data.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tms_dataset_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tms_dataset_data.key</code>.
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tms_dataset_data.key</code>.
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tms_dataset_data.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tms_dataset_data.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tms_dataset_data.dataset_id</code>.
     */
    public void setDatasetId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tms_dataset_data.dataset_id</code>.
     */
    public Long getDatasetId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JTmsDatasetDataRecord
     */
    public JTmsDatasetDataRecord() {
        super(JTmsDatasetData.TMS_DATASET_DATA);
    }

    /**
     * Create a detached, initialised JTmsDatasetDataRecord
     */
    public JTmsDatasetDataRecord(Long id, String key, String value, Long datasetId) {
        super(JTmsDatasetData.TMS_DATASET_DATA);

        setId(id);
        setKey(key);
        setValue(value);
        setDatasetId(datasetId);
        resetChangedOnNotNull();
    }
}
