/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JTmsStep;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JTmsStepRecord extends UpdatableRecordImpl<JTmsStepRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tms_step.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tms_step.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tms_step.instructions</code>.
     */
    public void setInstructions(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tms_step.instructions</code>.
     */
    public String getInstructions() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tms_step.expected_result</code>.
     */
    public void setExpectedResult(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tms_step.expected_result</code>.
     */
    public String getExpectedResult() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tms_step.steps_manual_scenario_id</code>.
     */
    public void setStepsManualScenarioId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tms_step.steps_manual_scenario_id</code>.
     */
    public Long getStepsManualScenarioId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JTmsStepRecord
     */
    public JTmsStepRecord() {
        super(JTmsStep.TMS_STEP);
    }

    /**
     * Create a detached, initialised JTmsStepRecord
     */
    public JTmsStepRecord(Long id, String instructions, String expectedResult, Long stepsManualScenarioId) {
        super(JTmsStep.TMS_STEP);

        setId(id);
        setInstructions(instructions);
        setExpectedResult(expectedResult);
        setStepsManualScenarioId(stepsManualScenarioId);
        resetChangedOnNotNull();
    }
}
