/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.enums.JTmsManualScenarioType;
import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JTmsManualScenario;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JTmsManualScenarioRecord extends UpdatableRecordImpl<JTmsManualScenarioRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tms_manual_scenario.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tms_manual_scenario.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>public.tms_manual_scenario.execution_estimation_time</code>.
     */
    public void setExecutionEstimationTime(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.tms_manual_scenario.execution_estimation_time</code>.
     */
    public Integer getExecutionEstimationTime() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.tms_manual_scenario.link_to_requirements</code>.
     */
    public void setLinkToRequirements(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tms_manual_scenario.link_to_requirements</code>.
     */
    public String getLinkToRequirements() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tms_manual_scenario.test_case_version_id</code>.
     */
    public void setTestCaseVersionId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tms_manual_scenario.test_case_version_id</code>.
     */
    public Long getTestCaseVersionId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.tms_manual_scenario.type</code>.
     */
    public void setType(JTmsManualScenarioType value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tms_manual_scenario.type</code>.
     */
    public JTmsManualScenarioType getType() {
        return (JTmsManualScenarioType) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JTmsManualScenarioRecord
     */
    public JTmsManualScenarioRecord() {
        super(JTmsManualScenario.TMS_MANUAL_SCENARIO);
    }

    /**
     * Create a detached, initialised JTmsManualScenarioRecord
     */
    public JTmsManualScenarioRecord(Long id, Integer executionEstimationTime, String linkToRequirements, Long testCaseVersionId, JTmsManualScenarioType type) {
        super(JTmsManualScenario.TMS_MANUAL_SCENARIO);

        setId(id);
        setExecutionEstimationTime(executionEstimationTime);
        setLinkToRequirements(linkToRequirements);
        setTestCaseVersionId(testCaseVersionId);
        setType(type);
        resetChangedOnNotNull();
    }
}
