/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JTmsTextManualScenario;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JTmsTextManualScenarioRecord extends UpdatableRecordImpl<JTmsTextManualScenarioRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.tms_text_manual_scenario.manual_scenario_id</code>.
     */
    public void setManualScenarioId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.tms_text_manual_scenario.manual_scenario_id</code>.
     */
    public Long getManualScenarioId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tms_text_manual_scenario.instructions</code>.
     */
    public void setInstructions(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tms_text_manual_scenario.instructions</code>.
     */
    public String getInstructions() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tms_text_manual_scenario.expected_result</code>.
     */
    public void setExpectedResult(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tms_text_manual_scenario.expected_result</code>.
     */
    public String getExpectedResult() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JTmsTextManualScenarioRecord
     */
    public JTmsTextManualScenarioRecord() {
        super(JTmsTextManualScenario.TMS_TEXT_MANUAL_SCENARIO);
    }

    /**
     * Create a detached, initialised JTmsTextManualScenarioRecord
     */
    public JTmsTextManualScenarioRecord(Long manualScenarioId, String instructions, String expectedResult) {
        super(JTmsTextManualScenario.TMS_TEXT_MANUAL_SCENARIO);

        setManualScenarioId(manualScenarioId);
        setInstructions(instructions);
        setExpectedResult(expectedResult);
        resetChangedOnNotNull();
    }
}
