/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.records;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.tables.JTmsProductVersion;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JTmsProductVersionRecord extends UpdatableRecordImpl<JTmsProductVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tms_product_version.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tms_product_version.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tms_product_version.documentation</code>.
     */
    public void setDocumentation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tms_product_version.documentation</code>.
     */
    public String getDocumentation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tms_product_version.version</code>.
     */
    public void setVersion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tms_product_version.version</code>.
     */
    public String getVersion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tms_product_version.project_id</code>.
     */
    public void setProjectId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tms_product_version.project_id</code>.
     */
    public Long getProjectId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JTmsProductVersionRecord
     */
    public JTmsProductVersionRecord() {
        super(JTmsProductVersion.TMS_PRODUCT_VERSION);
    }

    /**
     * Create a detached, initialised JTmsProductVersionRecord
     */
    public JTmsProductVersionRecord(Long id, String documentation, String version, Long projectId) {
        super(JTmsProductVersion.TMS_PRODUCT_VERSION);

        setId(id);
        setDocumentation(documentation);
        setVersion(version);
        setProjectId(projectId);
        resetChangedOnNotNull();
    }
}
