/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */

package com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.enums;


import com.epam.reportportal.serviceapi.infrastructure.persistence.jooq.JPublic;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public enum JTestItemTypeEnum implements EnumType {

  AFTER_CLASS("AFTER_CLASS"),

  AFTER_GROUPS("AFTER_GROUPS"),

  AFTER_METHOD("AFTER_METHOD"),

  AFTER_SUITE("AFTER_SUITE"),

  AFTER_TEST("AFTER_TEST"),

  BEFORE_CLASS("BEFORE_CLASS"),

  BEFORE_GROUPS("BEFORE_GROUPS"),

  BEFORE_METHOD("BEFORE_METHOD"),

  BEFORE_SUITE("BEFORE_SUITE"),

  BEFORE_TEST("BEFORE_TEST"),

  SCENARIO("SCENARIO"),

  STEP("STEP"),

  STORY("STORY"),

  SUITE("SUITE"),

  TEST("TEST");

  private final String literal;

  private JTestItemTypeEnum(String literal) {
    this.literal = literal;
  }

  @Override
  public Catalog getCatalog() {
    return getSchema().getCatalog();
  }

  @Override
  public Schema getSchema() {
    return JPublic.PUBLIC;
  }

  @Override
  public String getName() {
    return "test_item_type_enum";
  }

  @Override
  public String getLiteral() {
    return literal;
  }

  /**
   * Lookup a value of this EnumType by its literal. Returns
   * <code>null</code>, if no such value could be found, see {@link
   * EnumType#lookupLiteral(Class, String)}.
   */
  public static JTestItemTypeEnum lookupLiteral(String literal) {
    return EnumType.lookupLiteral(JTestItemTypeEnum.class, literal);
  }
}
